#!/usr/bin/env python3
"""
Build the display font's web assets from the TTF in font-src/.

Swapping the typeface is a one-command job: drop a new .ttf into font-src/,
delete the old one, and run this. It writes

    public/fonts/display.woff2   the face the page loads
    public/fonts/glyphs.json     outlines, for the SVG "outlines" export

under fixed names, so the stylesheet never has to change, and it rewrites the
generated block in public/js/state.js with the facts it read off the font:
family name, weight, generic fallback, and the cap-height ratio the optical
centring depends on. Those four drift silently if edited by hand — a wrong cap
ratio just sits every letter slightly off centre — so they are derived, never
typed.

    pip install fonttools brotli
    python3 tools/extract-glyphs.py
"""

import json
import re
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

ROOT = Path(__file__).resolve().parent.parent
FONT_SRC = ROOT / "font-src"
FONTS = ROOT / "public" / "fonts"
WOFF2 = FONTS / "display.woff2"
GLYPHS = FONTS / "glyphs.json"
STATE = ROOT / "public" / "js" / "state.js"

# printable ASCII, plus the punctuation a layout is likely to reach for
CHARS = [chr(c) for c in range(0x20, 0x7F)] + list(
    "–—‘’“”…•·°×÷€£¥©®™†‡§¶±≠≤≥→←↑↓"
)

BEGIN = "/* ── generated by tools/extract-glyphs.py ── */"
END = "/* ── end generated ── */"


def find_source() -> Path:
    candidates = sorted(
        p for p in FONT_SRC.glob("*") if p.suffix.lower() in (".ttf", ".otf")
    )
    if not candidates:
        sys.exit(f"No .ttf or .otf found in {FONT_SRC.relative_to(ROOT)}/")
    if len(candidates) > 1:
        names = ", ".join(p.name for p in candidates)
        sys.exit(f"Expected one font in font-src/, found {len(candidates)}: {names}")
    return candidates[0]


def name_record(font: TTFont, want: int) -> str:
    """Prefer the Windows/Unicode record, fall back to any."""
    for rec in font["name"].names:
        if rec.nameID == want and rec.platformID == 3:
            return rec.toUnicode()
    for rec in font["name"].names:
        if rec.nameID == want:
            return rec.toUnicode()
    return ""


def generic_family(font: TTFont) -> str:
    """Panose: family type 2 is Latin text, serif style 2-10 is a serif."""
    p = getattr(font["OS/2"], "panose", None)
    if p and p.bFamilyType == 2 and 2 <= p.bSerifStyle <= 10:
        return "serif"
    if p and p.bFamilyType == 3:
        return "cursive"
    return "sans-serif"


def patch_state(family: str, weight: int, cap_ratio: float, generic: str) -> None:
    source = STATE.read_text()
    block = "\n".join([
        BEGIN,
        f'export const FONT_FAMILY = "{family}";',
        f"export const FONT_WEIGHT = {weight};",
        "",
        "/* Centring is done on the cap height, so this has to match the font",
        "   in use or every letter sits slightly off centre in its cell. */",
        f"export const CAP_RATIO = {cap_ratio};",
        "",
        "/* On screen the face is loaded under the neutral alias `Display`,",
        "   which keeps the stylesheet independent of which font is in use.",
        "   Exports name the real family so the file resolves elsewhere. */",
        f'export const FONT_STACK = \'"Display", "{family}", {generic}\';',
        f"export const EXPORT_STACK = '\"{family}\", {generic}';",
        END,
    ])

    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(source):
        sys.exit(f"Could not find the generated block in {STATE.relative_to(ROOT)}")
    STATE.write_text(pattern.sub(lambda _: block, source))


def main() -> None:
    source = find_source()
    font = TTFont(source)
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    hmtx = font["hmtx"]
    upm = font["head"].unitsPerEm
    os2 = font["OS/2"]

    glyphs = {}
    missing = []
    for ch in CHARS:
        name = cmap.get(ord(ch))
        if name is None:
            missing.append(ch)
            continue
        pen = SVGPathPen(glyph_set)
        glyph_set[name].draw(pen)
        glyphs[ch] = {"d": pen.getCommands(), "aw": hmtx[name][0]}

    cap_height = getattr(os2, "sCapHeight", None) or os2.sTypoAscender
    data = {
        "unitsPerEm": upm,
        "capHeight": cap_height,
        "xHeight": getattr(os2, "sxHeight", None),
        "ascender": os2.sTypoAscender,
        "descender": os2.sTypoDescender,
        "glyphs": glyphs,
    }
    FONTS.mkdir(parents=True, exist_ok=True)
    GLYPHS.write_text(json.dumps(data, separators=(",", ":")))

    font.flavor = "woff2"
    font.save(WOFF2)

    family = name_record(font, 4) or name_record(font, 1)
    weight = os2.usWeightClass
    generic = generic_family(font)
    cap_ratio = round(cap_height / upm, 4)
    patch_state(family, weight, cap_ratio, generic)

    print(f"source   {source.relative_to(ROOT)}")
    print(f"family   {family}  ·  weight {weight}  ·  {generic}")
    print(f"cap      {cap_height}/{upm} = {cap_ratio}")
    print(f"{GLYPHS.relative_to(ROOT)}  {len(glyphs)} glyphs, {GLYPHS.stat().st_size:,} bytes")
    print(f"{WOFF2.relative_to(ROOT)}  {WOFF2.stat().st_size:,} bytes")
    print(f"{STATE.relative_to(ROOT)}  generated block rewritten")
    if missing:
        print(f"\nnot in this font, skipped: {''.join(missing)}")


if __name__ == "__main__":
    main()
